version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: helm-github-pages
          environment:
            - GITHUB_PAGES_REPO: wuzangsama/helm-charts
          command: wget -O - https://raw.githubusercontent.com/wuzangsama/charts/master/publish.sh | sh
